services:
  - type: web
    name: zipgrade-web-app
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    autoDeploy: true
